baseURL = "https://davlux.mansoorbarri.com"
languageCode = 'en-us'
title = "Davlux"
theme = "davlux"

[menu]
  [[menu.main]]
    name = "blogs"
    url = "/blogs"
    weight = 1

  [[menu.main]]
    name = "tags"
    url = "/tags"
    weight = 2

  [[menu.main]]
    name = "rss"
    url = "/rss"
    weight = 3

[params]
    wiki = "likh."
    hero = "a **hugo** theme, made with **Tailwind**."
    footer = "Davlux â€¢ 2024"
    mainSections = ["blogs"]
    projects = [    
        {name = "CS-Hugo", url = "https://github.com/mansoorbarri/coming-soon/", description = "A coming soon landing page made with Hugo"},       
        {name = "Hugo-Validator", url = "https://github.com/mansoorbarri/hugo-validator", description = "A theme submission validation script for Hugo"},       
        {name = "Aiman", url = "https://example.com", description = "Aiman Peman"},     
    ]
    socials = [        
    {name = "github", username = "mansorbarri"},       
    {name = "linkedin", username = "in/mansoorbarri"},       
    {name = "twitter", username = "mansoorbarri"},     
    ]




